
language: python

python:
  - { PATH: "{{Python37}}", VERSION: 3.7, DIST: std, PYINT: python3.7 }
  
virtualenv:
  - path: {{ospathjoin(root_path, pickname("$NAME_JENKINS", project_name + "_$VERSION_$DIST_$NAME"), "_venv")}}
  
install:
  - git submodule update --init --recursive
  - python -c "from pip._internal import main;main(\"install --no-cache-dir --no-deps --index http://localhost:8067/simple/ jyquickhelper pyquickhelper --extra-index-url=https://pypi.python.org/simple/\".split())"
  - python -c "from pip._internal import main;main(\"install --no-cache-dir --no-deps --index http://localhost:8067/simple/ csharpy>0.1.53 --extra-index-url=https://pypi.python.org/simple/\".split())"
  - python -c "from pip._internal import main;main(\"install -r requirements.txt\".split())"
  - python --version
  - python -c "from pip._internal import main;main([\"freeze\"])"
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
  # clean source
  - python -u clean_source.py
  # Build machinelearning
  - cd machinelearning
  - build -Debug
  - build -Release
  - cd ..
  # Copy binaries
  - cd machinelearning
  - dotnet publish Microsoft.ML.sln -o ../../dist/Debug -c Debug --self-contained || true
  - dotnet publish Microsoft.ML.sln -o ../../dist/Release -c Release --self-contained || true
  - cd ..
  - copy machinelearning\bin\x64.Debug\Native\*.so machinelearning\dist\Debug
  - copy machinelearning\bin\x64.Release\Native\*.so machinelearning\dist\Release
  # Build machinelearningext
  - cd machinelearningext
  - dotnet build -c Debug
  - dotnet build -c Release
  - cd ..

script:
  - { CMD: "cd machinelearningext;dotnet test -c Debug TestMachineLearningExt -v n;dotnet test -c Release TestMachineLearningExt -v n;cd ..", NAME: "UT_CSHARP" }

documentation:
  - if [ ${NAME} == "UT" ] then python -c "from sphinx import build_main;build_main(['-j2','-v','-T','-b','html','-d','docs/doctrees','docs/source','docs/build'])" fi
  - if [ ${NAME} == "UT" ] then xcopy docs\build\html dist\html fi
